import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
export const metadata: Metadata = {
  title: "MetaNode Stake",
  description: "Generated by create next app",
};
import Navbar from "@/components/layout/Navbar";
import Layout from "@/components/layout"
import 'react-toastify/dist/ReactToastify.css';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {/* <Navbar /> */}
          <Layout>
            {children}
          </Layout>
        </Provider>
      </body>
    </html>
  );
}
